-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 18:37:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rooms Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rooms Table` (
  `room_id` INT NOT NULL,
  `building_id` VARCHAR(45) NULL,
  `room_number` VARCHAR(45) NULL,
  `floor` VARCHAR(45) NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maintenance Ticket Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maintenance Ticket Table` (
  `ticket_id` INT NOT NULL,
  `room_id` INT NULL,
  `issue_description` TEXT(100) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(50) NULL,
  `resolved_at` TIMESTAMP(50) NULL,
  PRIMARY KEY (`ticket_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings Table` (
  `building_id` INT NULL,
  `building_name` VARCHAR(100) NULL,
  `adress` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  PRIMARY KEY (`building_id`),
  CONSTRAINT `fk_buildings`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`Rooms Table` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `maintenance_room_id`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`Maintenance Ticket Table` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
